insert into public.projects (title, description, tech_stack, live_url, featured, sort_order) values
('Crops and Resources Research and Development Center', 'A centralized web platform for research, extension, personnel, and administrative records, supporting institutional information access and operational workflows.', array['Next.js','React','TypeScript','JavaScript','Vercel','GitHub'], 'https://crrdc.vercel.app/', true, 1),
('Strengthening the M&E Capacity of CLAARRDEC in R&D through Database Management and Real Time Monitoring System (RTMS)', 'A centralized monitoring and evaluation system for CLAARRDEC reporting, research and development project tracking, data management, and oversight workflows across member institutions.', array['Laravel','PHP','MySQL','JavaScript','GitHub'], 'https://rtms.clsu.edu.ph/', true, 2),
('CLAARRDEC', 'A content management and e-library platform for public information delivery, authenticated access, library functions, administration, and visitor and user usage reporting.', array['Laravel','PHP','MySQL','JavaScript','GitHub'], 'https://claarrdec.clsu.edu.ph/', true, 3);

insert into public.skills (name, proficiency, sort_order) values
('PHP',0,1),('JavaScript',0,2),('TypeScript',0,3),('SQL',0,4),('Java',0,5),('React',0,6),('Next.js',0,7),('Laravel',0,8),('MySQL',0,9),('PostgreSQL',0,10),('Supabase',0,11),('n8n',0,12),('REST APIs',0,13),('Git',0,14),('GitHub',0,15),('Vercel',0,16),('ESP32',0,17),('Arduino',0,18),('PlatformIO',0,19),('ArcGIS',0,20),('QGIS',0,21);

insert into public.timeline_entries (type, organization, role, description, start_date, end_date, sort_order) values
('experience','Independent and collaborative product work','Full-Stack Web Developer','Building web applications, APIs, databases, and n8n automation workflows using Next.js, Laravel, React, and Supabase.','2026',null,1),
('experience','Central Luzon State University','Researcher, Instructor, and Information Systems Developer','Led and co-developed institutional research and monitoring systems while serving as project lead or technical lead on government-funded initiatives. Coordinated with 3-5 person project teams, researchers, and institutional stakeholders (DOST-PCAARRD, DA-BPI, CLSU various research departments) to translate operational requirements into scalable software solutions. Conducted project planning, requirements gathering, and regular team coordination meetings. Delivered research information platforms, monitoring and evaluation systems, content management, and smart agriculture applications. Also taught undergraduate programming and supervised capstone projects.','2019','2026',2),
('experience','Central Luzon State University','Project Technical Staff','Provided technical and administrative support for institutional operations and government-funded research projects. Contributed to requirements analysis, documentation, and technical coordination for multi-disciplinary project teams. Managed project records, technical reports, and stakeholder communications to support project planning, risk assessment, and reporting workflows.','2017','2019',3),
('education','Nueva Ecija University of Science and Technology','Master of Science in Information Technology, Major in Data Science','Graduate study in Information Technology with a major in Data Science.','2026',null,4),
('education','Central Luzon State University','Bachelor of Science in Information Technology, Major in Systems Development','Undergraduate degree in Information Technology with a major in Systems Development.','2013','2017',5);
