create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  image_url text,
  tech_stack text[] not null default '{}',
  live_url text,
  github_url text,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  proficiency integer not null default 0 check (proficiency between 0 and 100),
  icon text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.timeline_entries (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('experience', 'education')),
  organization text not null,
  role text not null,
  description text not null,
  start_date text not null,
  end_date text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.projects enable row level security;
alter table public.skills enable row level security;
alter table public.timeline_entries enable row level security;

revoke all on public.admin_users from anon, authenticated;
grant select on public.admin_users to authenticated;
grant select on public.projects, public.skills, public.timeline_entries to anon, authenticated;
grant insert, update, delete on public.projects, public.skills, public.timeline_entries to authenticated;
grant usage, select on sequence public.projects_id_seq, public.skills_id_seq, public.timeline_entries_id_seq to authenticated;

create policy "Admins can see their own membership"
  on public.admin_users for select to authenticated
  using (user_id = (select auth.uid()));

create policy "Portfolio is public to read"
  on public.projects for select to anon, authenticated using (true);
create policy "Portfolio is public to read"
  on public.skills for select to anon, authenticated using (true);
create policy "Portfolio is public to read"
  on public.timeline_entries for select to anon, authenticated using (true);

create policy "Only allowlisted admins can insert projects"
  on public.projects for insert to authenticated
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
create policy "Only allowlisted admins can update projects"
  on public.projects for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
create policy "Only allowlisted admins can delete projects"
  on public.projects for delete to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

create policy "Only allowlisted admins can insert skills"
  on public.skills for insert to authenticated
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
create policy "Only allowlisted admins can update skills"
  on public.skills for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
create policy "Only allowlisted admins can delete skills"
  on public.skills for delete to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())));

create policy "Only allowlisted admins can insert timeline entries"
  on public.timeline_entries for insert to authenticated
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
create policy "Only allowlisted admins can update timeline entries"
  on public.timeline_entries for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())))
  with check (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
create policy "Only allowlisted admins can delete timeline entries"
  on public.timeline_entries for delete to authenticated
  using (exists (select 1 from public.admin_users where user_id = (select auth.uid())));
